const sampleListings = [
  {
    title: "Cozy Studio in Bandra West",
    description: "A bright and modern studio apartment in the heart of Bandra West. Walking distance to cafes, restaurants, and the beach. Perfect for solo travelers or couples.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    price: 2500,
    location: "Bandra West, Mumbai",
    country: "India",
    category: "Studio",
    rooms: 1,
    amenities: ["WiFi", "AC", "Kitchen", "Hot Water"],
  },
  {
    title: "Spacious 2BHK in Koramangala",
    description: "Well-furnished 2BHK apartment in Koramangala, close to tech parks, shopping malls and restaurants. Great for business travelers or families.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
    price: 3500,
    location: "Koramangala, Bengaluru",
    country: "India",
    category: "Apartment",
    rooms: 2,
    amenities: ["WiFi", "AC", "Washing Machine", "Parking", "Kitchen"],
  },
  {
    title: "Heritage Villa Near Lakes",
    description: "Stunning heritage villa with lake views in Udaipur. Experience royal Rajasthani hospitality with modern amenities. Ideal for a getaway.",
    image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80",
    price: 8500,
    location: "City Palace Area, Udaipur",
    country: "India",
    category: "Villa",
    rooms: 3,
    amenities: ["WiFi", "Pool", "Breakfast", "AC", "Room Service", "Parking"],
  },
  {
    title: "Mountain Cabin in Manali",
    description: "Charming wooden cabin nestled in the Himalayas with breathtaking mountain views. Perfect for trekkers, adventure lovers and those seeking peace.",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&q=80",
    price: 4200,
    location: "Old Manali",
    country: "India",
    category: "Cabin",
    rooms: 2,
    amenities: ["Fireplace", "Mountain View", "Hot Water", "Breakfast"],
  },
  {
    title: "Budget Hostel in Paharganj",
    description: "Clean, safe and friendly hostel in central Delhi. Great place to meet fellow travelers. Minutes from New Delhi Railway Station.",
    image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80",
    price: 800,
    location: "Paharganj, Delhi",
    country: "India",
    category: "Hostel",
    rooms: 1,
    amenities: ["WiFi", "Locker", "Common Kitchen", "24hr Reception"],
  },
  {
    title: "Luxury Penthouse in Hiranandani",
    description: "Premium penthouse with city views and top-of-the-line amenities. A sophisticated retreat in Mumbai's most upscale township.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    price: 12000,
    location: "Hiranandani Gardens, Powai",
    country: "India",
    category: "Apartment",
    rooms: 4,
    amenities: ["WiFi", "Gym", "Pool", "AC", "Parking", "Concierge", "Home Theater"],
  },
];

module.exports = { sampleListings };
